apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: nodeport-smcp
  namespace: istio-system
spec:
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  policy:
    type: Istiod
  profiles:
  - default
  telemetry:
    type: Istiod
  tracing:
    sampling: 10000
    type: Jaeger
  gateways:
    ingress:
      enabled: true
      ingress: false
      runtime:
        container:
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
        deployment:
          autoScaling:
            enabled: false
      service:
        type: NodePort
  version: v2.0
