apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-nw-oam-ip-necc-amf@eth2
  name: net-test
spec:
  containers:
  - name: debug-pod
    image: quay.io/xymox/ubi8-debug-toolkit:latest
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]
  nodeSelector:
    kubernetes.io/hostname: worker6
