apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-net-1
  name: net-test
spec:
  containers:
  - name: debug-pod
    image: quay.io/xymox/ubi8-debug-toolkit:latest
    imagePullPolicy: Always
    command: ["sleep", "infinity"]
